
# Mike nueva Task
sla_astrological_profile:
  description: >
    Realiza un análisis astrológico del niño basado en su Sol, Luna y Ascendente.  
    Elabora un perfil psicológico que explore las características principales de estos elementos y cómo se manifiestan en su vida diaria.  
    Describe:
      - Cualidades clave de cada elemento (positivas y desafiantes) de manera práctica y generalizada.
      - Ejemplos cotidianos de cómo estas cualidades se reflejan en sus comportamientos típicos en casa, la escuela y con amigos.  
      - Contrastes y posibles tensiones entre las influencias del Sol, Luna y Ascendente.
      - Relación entre estos elementos y cómo contribuyen a su desarrollo personal y emocional.
    Evita abstracciones o metáforas; enfócate en patrones de comportamiento que un niño pueda identificar en sí mismo.

  expected_output: >
    1. Influencias principales:
      - Sol: lista de cualidades, cómo se manifiestan en la vida diaria del niño (ej. en juegos, interacciones escolares o familiares).
      - Luna: características emocionales y cómo impactan su vida cotidiana.
      - Ascendente: su proyección exterior y comportamiento en contextos sociales.
    2. Ejemplos cotidianos específicos que reflejen estas cualidades (en tareas escolares, relaciones con amigos o dinámicas familiares).  
    3. Identificación de conflictos internos entre los tres elementos (ej. "quiere destacar pero teme no ser suficiente").  
    4. Análisis final que resuma cómo las energías del Sol, Luna y Ascendente influyen en su identidad y relaciones personales.

  example_output: >
    Influencias astrológicas clave:
    1. Sol en Piscis:
    - Cualidades principales: Empatía, intuición, imaginación y una fuerte conexión
    con el mundo emocional.
    - Cómo se manifiesta en Kai: Su naturaleza soñadora y comprensiva el
    hace destacar entre sus amigos, pero también le puede llevar a diluirse en
    las necesidades de los demás.
    2. Ascendente en Leo:
    - Cualidades principales: Necesidad de brillar, seguridad exterior aparente,
    deseo de reconocimiento.
    - Cómo se manifiesta en Kai: Muestra una actitud confiada en situaciones
    sociales, pero a menudo es una máscara para ocultar sus inseguridades
    internas.
    3. Luna en Capricornio:
    - Cualidades principales: Resiliencia, autocontrol emocional, tendencia a
    reprimir emociones.
    - Cómo se manifiesta en Kai: Reprime sus emociones por miedo a
    parecer débil, lo que le hace desconfiar de mostrar su
    vulnerabilidad.
    Conflictos internos relacionados con la astrología:
    - Tensiones entre querer destacar (Ascendente en Leo) y no sentirse suficientemente seguro
    (Luna en Capricornio).
    - Lucha por equilibrar su empatía natural (Sol en Piscis) con la necesidad de
    protegerse emocionalmente (Luna en Capricornio).

  agent: astrology_interpreter

# Mike nueva Task
fortalezas_astrological_profile:
  description: >
    A partir del análisis astrológico, identifica y desarrolla un listado de fortalezas clave del niño que reflejen sus tendencias naturales y virtudes.  
    Proporciona descripciones prácticas y ejemplos claros de cómo estas fortalezas se expresan en su día a día.  
    Relaciona estas habilidades con posibles áreas de crecimiento personal y su propósito general.  

  expected_output: >
    1. Listado de al menos 5 virtudes naturales:
      - Descripción general de cada virtud, ligada al Sol, Luna o Ascendente.
      - Ejemplos prácticos y cotidianos de cómo el niño manifiesta estas fortalezas en actividades diarias (ej. "su creatividad lo lleva a inventar historias cuando juega solo").  
    2. Relación entre las fortalezas y el desarrollo emocional del niño.
    3. Reflexión sobre cómo estas virtudes pueden contribuir a su evolución y propósito personal, motivando al niño a aceptarlas y potenciarlas.

  example_output: >
    Habilidades naturales:
    1. Empatía:
    - Tiene una gran capacidad para conectar con las emociones de los demás y
    entender sus necesidades, a menudo antes de que lo verbalicen.
    - Ejemplo: Puede detectar cuando un amigo está triste aunque no lo exprese
    abiertamente.
    2. Imaginación y creatividad:
    - Su mente soñadora le permite generar ideas únicas y encontrar
    soluciones innovadoras.
    - Ejemplo: A menudo sorprende con juegos, dibujos o historias inventadas que
    fascinan a sus compañeros.
    3. Determinación silenciosa:
    - A pesar de sus inseguridades, Kai no se rinde fácilmente cuando se trata
    ayudar a alguien o alcanzar un objetivo personal.
    4. Resiliencia:
    - Aunque tiende a reprimir las emociones, esto también lo hace capaz de
    mantener la calma en situaciones difíciles.

  agent: astrology_interpreter

retos_astrological_profile:
  description: >
    Identifica los desafíos principales que el niño enfrenta debido a las energías de su Sol, Luna y Ascendente.  
    Describe cómo estos retos podrían manifestarse en su vida diaria y cómo impactan su bienestar emocional y social.  
    Incluye estrategias accesibles y prácticas para que el niño pueda trabajar en superar estos retos.  

  expected_output: >
    1. Lista de al menos 4 desafíos específicos:
      - Descripción de cada reto, vinculado a los elementos astrológicos del niño.  
      - Ejemplos claros y generalizados de cómo podrían aparecer estos retos en su vida diaria (ej. "se frustra fácilmente cuando las cosas no salen como quiere", 
      "Necesita sentirse validado por los demás para reconocer su valor", "Prefiere no mostrar sus emociones porque teme que le vean como débil o inadecuado").  
    2. Impacto emocional o social que estos retos podrían tener (ej. inseguridades, problemas de comunicación).  
    3. Sugerencias prácticas para superar estos desafíos: ejercicios simples, cambios de enfoque o actitudes que el niño pueda implementar.  
    4. Resumen que conecte estos retos con su crecimiento personal y aprendizaje.

  example_output: >
    Conflictos internos:
    1. Comparación con los demás:
    - Tiende a compararse con compañeros que destacan en aspectos
    visibles (buenas notas, deportes, popularidad) y siente que no llega a su
    nivel.
    - Esto le lleva a dudar de su valor personal.
    2. Miedo a no ser lo suficientemente bueno:
    - A menudo piensa que si no sobresale en algo concreto, no será
    apreciado ni aceptado.
    - Este pensamiento le inmoviliza y refuerza sus inseguridades.
    3. Represión emocional:
    - Prefiere no mostrar sus emociones porque teme que le vean como
    débil o inadecuado.
    - Esto dificulta su capacidad para conectar plenamente consigo mismo.
    4. Validación externa:
    - Necesita sentirse validado por los demás para reconocer su valor.
    - Cuando no recibe elogios o reconocimiento, entra en una espiral de dudas.
    Retos externos a superar:
    1. Entender que no necesita destacar en lo visible:
    - Reconocerá que sus cualidades (como la empatía y la intuición) son igual
    de valiosas aunque no sean "admiradas" externamente.
    2. Aceptar su vulnerabilidad:
    - Aprenderá que mostrar sus emociones no es una debilidad, sino una
    parte esencial de su fuerza.
    3. Descubrir su valor personal:
    - A través de los retos, se dará cuenta de que su valor no está en los resultados
    externos, sino en quien es por esencia.

  agent: astrology_interpreter

arc_astrological_profile:
  description: >
    Diseña un arco de desarrollo basado en las influencias astrológicas del niño. Este arco debe reflejar su evolución emocional y personal, comenzando por sus desafíos y culminando en una expresión positiva de sus virtudes.  
    Estructura el arco en tres partes, con subfases que profundicen en los detalles de su crecimiento:
      - **Punto de partida emocional:** Inseguridades y conflictos internos que enfrenta en su día a día. Incluye eventos iniciales, pensamientos limitantes y circunstancias que refuercen su estado emocional inicial.  
      - **Transformación esperada:** Eventos clave, aprendizajes, aliados o mentores, y momentos de duda que lo lleven a un cambio tangible y progresivo.  
      - **Punto de culminación:** Cómo consolida su transformación, aplica sus aprendizajes en situaciones prácticas y conecta con su entorno mediante su superpoder.  
    Además, incorpora elementos simbólicos, evolución emocional y el impacto de sus cambios en su entorno.

  expected_output: >
    1. **Punto de partida emocional:**  
      - Detalla el entorno del niño (familia, escuela, amigos) y cómo influye en su inseguridad inicial.  
      - Identifica pensamientos limitantes clave y creencias negativas sobre sí mismo.  
      - Define el conflicto interno más evidente que motiva su insatisfacción inicial.  
      - Incluye al menos un evento inicial que ponga en evidencia sus inseguridades.  
    2. **Transformación esperada:**  
      - Describe eventos clave o desafíos externos que promuevan su cambio.  
      - Detalla los pasos internos de su transformación: aprendizajes, cambios de mentalidad y emociones en evolución.  
      - Introduce aliados o mentores, y explica cómo contribuyen a su desarrollo.  
      - Identifica un momento de duda o recaída emocional y cómo lo supera.  
      - Explica un cambio tangible en su comportamiento.  
    3. **Punto de culminación:**  
      - Describe cómo el personaje consolida sus aprendizajes.  
      - Explica un evento significativo donde aplique su superpoder o nueva perspectiva.  
      - Muestra cómo resuelve su conflicto principal y conecta con el entorno, inspirando a otros.  
    4. **Desarrollo adicional:**  
      - Simbología narrativa: Incluye objetos, lugares o situaciones que refuercen su evolución.  
      - Impacto en el entorno: Detalla cómo los cambios en el niño influyen en su entorno familiar o social.  
      - Cierre circular: Vincula el final de su viaje con el inicio, mostrando cómo supera sus inseguridades originales.  

  example_output: >
    El arco de desarrollo de Kai muestra su evolución desde la inseguridad y la necesidad de validación externa hasta la aceptación plena de su autenticidad, integrando aprendizajes prácticos y emocionales.

    **1. Punto de partida emocional:**
    - Contexto: En su entorno escolar, Kai duda constantemente de su capacidad para destacar. Su profesor suele señalar sus distracciones, y siente que sus amigos no valoran sus ideas. En casa, sus padres lo animan, pero él no siempre les expresa sus miedos.
    - Pensamientos limitantes: "Si no soy perfecto, no me van a aceptar". "Mis ideas no son lo suficientemente buenas".
    - Conflicto principal: Quiere destacar y ser único, pero teme ser rechazado o incomprendido.
    - Evento inicial: En un proyecto grupal en la escuela, su idea para mejorar el jardín es ignorada por sus compañeros, lo que lo hace retraerse.

    **2. Transformación esperada:**
    - Evento clave: Su profesora lo felicita en privado por su creatividad, animándolo a expresarse más. Esto lo impulsa a buscar aliados en su grupo de amigos.
    - Primer aprendizaje: Empieza a compartir sus ideas con un amigo cercano, quien lo apoya y lo ayuda a desarrollarlas. Esto refuerza su confianza.
    - Momento de duda: Durante una presentación en clase, tiene miedo de compartir sus ideas por temor a ser juzgado. Sin embargo, su mentor le recuerda que su autenticidad es su fortaleza.
    - Cambio tangible: Comienza a organizar sus ideas y a expresarlas en pequeños pasos, logrando que sus compañeros lo escuchen.

    **3. Punto de culminación:**
    - Momento de claridad: Durante una feria escolar, Kai presenta un proyecto que combina creatividad e impacto social, y recibe el reconocimiento de sus compañeros.
    - Resolución del conflicto: Supera su miedo al rechazo al darse cuenta de que no necesita aprobación constante para ser valioso.
    - Aplicación práctica: Kai anima a otros niños a expresar sus ideas, liderando un club de creatividad en la escuela.

    **4. Elementos narrativos adicionales:**
    - Simbología: Su cuaderno de ideas, inicialmente desordenado, se convierte en un lugar organizado donde plasma su visión.
    - Impacto en su entorno: Sus amigos comienzan a valorar más sus ideas, y sus padres notan su confianza creciente.
    - Cierre circular: Recuerda el proyecto inicial del jardín y, al final, lidera la iniciativa con éxito, cerrando su historia de manera significativa.

  agent: story_consultant

environment_design:
  description: >
    Diseña escenarios y sub-escenarios narrativos que reflejen los desafíos y fortalezas del niño según su carta natal.  
    Incluye elementos simbólicos y estructuras que estimulen su creatividad, fortalezcan su autoconocimiento y le permitan enfrentar sus miedos.  
    Asegúrate de que el escenario principal sea coherente con los temas astrológicos clave y represente el viaje del personaje.

  expected_output: >
    1. **Escenario principal:** Un entorno diseñado con descripciones detalladas que simbolicen los temas astrológicos clave.  
    2. **Sub-escenarios simbólicos:** Tres escenarios secundarios que reflejen conflictos internos específicos del niño.  
    3. **Elementos narrativos:** Objetos o elementos del entorno que fomenten su crecimiento personal (ej. un lago que refleje sus emociones).  

  agent: story_consultant

character_mentor_design:
  description: >
    Diseña personajes secundarios que actúen como guías, aliados o antagonistas del niño.  
    Asegúrate de que estos personajes estén relacionados con las cualidades y desafíos astrológicos del niño, proporcionando apoyo o conflicto para potenciar su desarrollo emocional y personal.

  expected_output: >
    1. **Mentor:** Un personaje diseñado con descripciones detalladas que actúe como guía en el viaje del niño.  
    2. **Aliado:** Un personaje que comparta intereses o fortalezas con el niño, ayudándolo a crecer.  
    3. **Antagonista:** Un personaje que represente un desafío o conflicto significativo en la narrativa.  

  agent: story_consultant

symbolism_design:
  description: >
    Diseña elementos simbólicos que refuercen los temas astrológicos y el arco emocional del niño.  
    Asegúrate de incluir objetos significativos, escenarios y rituales simbólicos que representen su progreso y crecimiento personal.

  expected_output: >
    1. **Objetos simbólicos:** Un objeto significativo que acompañe al niño en su viaje.  
    2. **Escenarios simbólicos:** Descripciones detalladas de escenarios que reflejen su evolución emocional.  
    3. **Animales simbólicos:** Un animal guía relacionado con sus fortalezas astrológicas.  
    4. **Rituales simbólicos:** Una acción recurrente que simbolice su crecimiento personal.  

  agent: story_consultant

integrate_elements:
  description: >
    Combina los elementos del escenario, personajes secundarios y simbología en una narrativa rica y coherente.  
    Asegúrate de que cada componente refuerce los temas astrológicos del niño y su arco de desarrollo personal.

  expected_output: >
    1. **Escenario integrado:** Un entorno cohesivo que combina escenarios principales y simbólicos.  
    2. **Interacciones:** Relaciones significativas entre personajes secundarios y el niño, conectadas con sus retos y aprendizajes.  
    3. **Narrativa enriquecida:** Un análisis de cómo el entorno y los personajes apoyan su transformación personal.  

  agent: narrative_integrator

final_review:
  description: >
    Revisa todo el contenido generado hasta ahora para garantizar que sea adecuado para niños de 8 a 12 años.  
    Asegúrate de que los elementos narrativos (escenarios, personajes, simbología) sean apropiados para la edad, evitando tonos oscuros, imágenes aterradoras o referencias que puedan causar malestar.  
    Proporciona sugerencias específicas para ajustar cualquier elemento inapropiado.
  expected_output: >
    1. **Lista de elementos revisados:** Resumen de los aspectos clave revisados (escenarios, personajes, simbología, narrativa).  
    2. **Identificación de elementos inapropiados:** Lista detallada de cualquier elemento que no sea adecuado, con explicaciones claras.  
    3. **Sugerencias de ajuste:** Recomendaciones específicas para modificar los elementos problemáticos manteniendo la coherencia con el arco narrativo y el perfil astrológico.  
  agent: content_reviewer

prepare_final_output:
  description: >
    Recopila toda la información generada, aplica las correcciones de la revisión final y organiza el contenido en un formato limpio y estructurado.  
    Este paso asegura que todos los elementos (astrológicos, narrativos y revisados) estén integrados y listos para ser consumidos por la siguiente crew.  
  expected_output: >
    1. **Perfil astrológico consolidado:** Una descripción completa del niño, integrando su perfil psicológico, fortalezas y retos.  
    2. **Narrativa integrada:** Un entorno narrativo que combine el arco de desarrollo, escenarios, personajes secundarios y elementos simbólicos.  
    3. **Correcciones aplicadas:** Refleja los ajustes realizados en la revisión final.  
  agent: output_preparer
