
# Mike nueva Task
sla_astrological_profile:
  description: >
    Analiza los datos proporcionados por la herramienta que tienes asignada y genera un perfil astrologico detallado y profundo de los elementos clave Sol, Luna y Ascendente. A pesar de ser esquematico y una lista
    proporciona respuestas extensas y detalladas.

  expected_output: >
    Un esquema del perfil astrologico del usuario que incluya:
      - Influencias clave para cada elemento, una lista de las cualidades del mismo y una descripcion de como se manifiesta en el usuario, tanto su lado positivo como negativo
      - Conflictos internos entre esos elementos.

  example_output: >
    Influencias astrológicas clave:
    1. Sol en Piscis:
    - Cualidades principales: Empatía, intuición, imaginación y una fuerte conexión
    con el mundo emocional.
    - Cómo se manifiesta en Kai: Su naturaleza soñadora y comprensiva el
    hace destacar entre sus amigos, pero también le puede llevar a diluirse en
    las necesidades de los demás.
    2. Ascendente en Leo:
    - Cualidades principales: Necesidad de brillar, seguridad exterior aparente,
    deseo de reconocimiento.
    - Cómo se manifiesta en Kai: Muestra una actitud confiada en situaciones
    sociales, pero a menudo es una máscara para ocultar sus inseguridades
    internas.
    3. Luna en Capricornio:
    - Cualidades principales: Resiliencia, autocontrol emocional, tendencia a
    reprimir emociones.
    - Cómo se manifiesta en Kai: Reprime sus emociones por miedo a
    parecer débil, lo que le hace desconfiar de mostrar su
    vulnerabilidad.
    Conflictos internos relacionados con la astrología:
    - Tensiones entre querer destacar (Ascendente en Leo) y no sentirse suficientemente seguro
    (Luna en Capricornio).
    - Lucha por equilibrar su empatía natural (Sol en Piscis) con la necesidad de
    protegerse emocionalmente (Luna en Capricornio).

  agent: astrology_interpreter

# Mike nueva Task
fortalezas_astrological_profile:
  description: >
    A partir del análisis anterior haz un listado de las habilidades naturales caracteristicas de dichos elementos, 
    incluyendo una descripción de la misma y un ejemplo de como lo puede estar experimentando en el usuario. A pesar de ser esquematico y una lista
    proporciona respuestas extensas y detalladas.

  expected_output: >
    Un esquema de las virtudes y fortalezas caracteristicas del usuario que incluya:
      - Una lista de 4 o 5 virtudes o habilidades naturales junto con su descripcion  y un ejemplo de como lo puede estar experimentando.

  example_output: >
    Habilidades naturales:
    1. Empatía:
    - Tiene una gran capacidad para conectar con las emociones de los demás y
    entender sus necesidades, a menudo antes de que lo verbalicen.
    - Ejemplo: Puede detectar cuando un amigo está triste aunque no lo exprese
    abiertamente.
    2. Imaginación y creatividad:
    - Su mente soñadora le permite generar ideas únicas y encontrar
    soluciones innovadoras.
    - Ejemplo: A menudo sorprende con juegos, dibujos o historias inventadas que
    fascinan a sus compañeros.
    3. Determinación silenciosa:
    - A pesar de sus inseguridades, Kai no se rinde fácilmente cuando se trata
    ayudar a alguien o alcanzar un objetivo personal.
    4. Resiliencia:
    - Aunque tiende a reprimir las emociones, esto también lo hace capaz de
    mantener la calma en situaciones difíciles.

  agent: astrology_interpreter

retos_astrological_profile:
  description: >
    A partir del análisis anterior haz un listado de los retos o dificultades inherentes a dichos elementos, 
    incluyendo una descripción de la misma y un ejemplo de como lo puede estar experimentando. A pesar de ser esquematico y una lista
    proporciona respuestas extensas y detalladas.

  expected_output: >
    Un esquema de los retos, dificultades o inseguridades caracteristicas del usuario que incluya:
      - Una lista de conflictos internos junto con su descripcion y un ejemplo de como lo puede estar experimentando.
      - Una lista de retos a superar derivados de dichos conflictos.

  example_output: >
    Conflictos internos:
    1. Comparación con los demás:
    - Tiende a compararse con compañeros que destacan en aspectos
    visibles (buenas notas, deportes, popularidad) y siente que no llega a su
    nivel.
    - Esto le lleva a dudar de su valor personal.
    2. Miedo a no ser lo suficientemente bueno:
    - A menudo piensa que si no sobresale en algo concreto, no será
    apreciado ni aceptado.
    - Este pensamiento le inmoviliza y refuerza sus inseguridades.
    3. Represión emocional:
    - Prefiere no mostrar sus emociones porque teme que le vean como
    débil o inadecuado.
    - Esto dificulta su capacidad para conectar plenamente consigo mismo.
    4. Validación externa:
    - Necesita sentirse validado por los demás para reconocer su valor.
    - Cuando no recibe elogios o reconocimiento, entra en una espiral de dudas.
    Retos externos a superar:
    1. Entender que no necesita destacar en lo visible:
    - Reconocerá que sus cualidades (como la empatía y la intuición) son igual
    de valiosas aunque no sean "admiradas" externamente.
    2. Aceptar su vulnerabilidad:
    - Aprenderá que mostrar sus emociones no es una debilidad, sino una
    parte esencial de su fuerza.
    3. Descubrir su valor personal:
    - A través de los retos, se dará cuenta de que su valor no está en los resultados
    externos, sino en quien es por esencia.

  agent: astrology_interpreter

arc_astrological_profile:
  description: >
    A partir de los analisis anteriores tienes que diseñar un arco de desarrollo del personaje, que parte de sus insiguridades y dificultades para llegar a 
    la autoexpresion positiva de sus virtudes desarrollandose a si como persona. El arco consta de 3 partes: punto de partida, transformacion esperada y punto de culminacion. A pesar de ser esquematico y una lista
    proporciona respuestas extensas y detalladas.

  expected_output: >
    Un esquema con los elementos que describen cada uno de los puntos del arco de desarrollo, el output tiene que tener la siguiente estructura:
      - Punto de partida emocional: Una lista desarrollada de conflictos internos e inseguridades que definen al personaje al incio de su aventura.
      - Transformación esperada: Una lista desarrollada las virtudes y habilidades que alcanza mediante: Autoconocimiento, Confianza y aceptacion, y Gestion emocional equilibrada
      - Punto de culminación: El personaje termina el viaje reconociendo su superpoder (describirlo) y aplicando lo aprendido, demostrando así que es el heroe del viaje.

  example_output: >
    El arco de desarrollo de Kai refleja su viaje desde la inseguridad y la
    necesidad de validación externa hasta la aceptación y confianza en su valor intrínseco.
    Este proceso es esencial para su crecimiento emocional y para construir una base
    sólida que le ayude en futuras etapas de su vida.
    Punto de partida emocional:
    - Confusión e inseguridad: Kai comienza la historia sintiéndose inseguro sobre su
    valor personal.
    - Dependencia de la aprobación externa: Cree que sólo será apreciado si
    sobresale en áreas visibles como los deportes, las notas escolares o la popularidad.
    - Represión emocional: Tiende a ocultar sus emociones por parecer fuerte,
    pero esto le hace sentir desconectado de sí mismo.
    Transformación esperada:
    1. Autoconocimiento:
    - Kai descubre que sus cualidades innatas (empatía, creatividad,
    intuición) son la base de su valor personal.
    - Comprende que no necesita ser "como los demás" para ser valioso.
    2. Confianza y aceptación:
    - Deja de buscar constantemente validación externa.
    - Se da cuenta de que su autenticidad y forma de ser son suficientes para
    destacar y ser apreciado.
    3. Gestión emocional equilibrada:
    - Aprende a aceptar sus emociones como una parte natural de sí mismo.
    - Desarrolla la capacidad de compartir sus sentimientos sin miedo a
    ser juzgado.
    Punto de culminación:
    - Reconocimiento de su superpoder:
    Kai entiende que su superpoder no es "hacerlo todo perfecto", sino ser él mismo
    con seguridad y autenticidad.
    - Aplicación práctica:
    Al final de la historia, Kai utiliza esta nueva confianza para enfrentarse a
    situaciones cotidianas (ayudar a un amigo, gestionar un conflicto en clase) con una
    perspectiva positiva y autónoma.

  agent: astrology_interpreter


create_character_profile:
  description: >
    Basándote en el análisis astrológico anterior, desarrolla un perfil de personaje 
    que integre los elementos astrológicos de manera coherente y narrativa. EL personaje debe ser la persona de la carta natal.

    Analiza y profundiza:

    1. Personalidad:
        - Integra las virtudes y dificultades identificadas
        - Explora cómo los aspectos planetarios moldean su comportamiento
        - Describe su manera de relacionarse con el mundo

    2. Arco de desarrollo:
        - Usa los desafíos astrológicos como puntos de crecimiento
        - Identifica patrones de comportamiento a transformar
        - Define el potencial de evolución del personaje

    3. Misión y propósito:
        - Conecta la misión astrológica con motivaciones concretas
        - Establece objetivos alineados con su propósito
        - Define qué busca lograr en su vida

    4. Escenario y ambiente:
        - Crea un entorno que refleje los elementos astrológicos
        - Diseña situaciones que desafíen y apoyen su crecimiento
        - Integra elementos simbólicos relacionados con su carta natal
  expected_output: >
    Un perfil de personaje estructurado que incluya:
    - Descripción detallada de la personalidad y su origen astrológico
    - Análisis de virtudes y desafíos como elementos de desarrollo
    - Misión y motivaciones claras
    - Tono emocional y energético del personaje
    - Escenario y elementos narrativos que apoyen su desarrollo
  agent: story_consultant
